# GTEx Gene Expression Data Exploration

This notebook is used to explore the GTEx V11 median TPM gene expression dataset.

The goal is to understand the structure of the data, check the genes and tissues, and prepare the dataset for further analysis.

In [1]:
%pip install pandas numpy matplotlib

Requirement already satisfied: pandas in c:\users\benso\appdata\local\programs\python\python312\lib\site-packages (3.0.1)
Requirement already satisfied: numpy in c:\users\benso\appdata\local\programs\python\python312\lib\site-packages (2.4.3)
Requirement already satisfied: matplotlib in c:\users\benso\appdata\local\programs\python\python312\lib\site-packages (3.11.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\benso\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\benso\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\benso\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\users\benso\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\benso\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (4.66.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\benso\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\benso\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=9 in c:\users\benso\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\benso\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: six>=1.5 in c:\users\benso\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
file_name = "../data/GTEx_Analysis_2025-08-22_v11_RNASeQCv2.4.3_gene_median_tpm.gct.gz"

df = pd.read_csv(
    file_name,
    sep="\t",
    skiprows=2
)

df.head()

,Name,Description,Adipose_Subcutaneous,Adipose_Visceral_Omentum,Adrenal_Gland,Artery_Aorta,Artery_Coronary,Artery_Tibial,Bladder,Brain_Amygdala,...,Spleen,Stomach,Stomach_Mixed_Cell,Stomach_Mucosa,Stomach_Muscularis,Testis,Thyroid,Uterus,Vagina,Whole_Blood
0,ENSG00000290825.2,DDX11L16,0.00000,0.0000,0.00000,0.0000,0.00000,0.00000,0.00000,0.011780,...,0.00000,0.00000,0.014928,0.012652,0.015991,0.073208,0.00000,0.00000,0.00000,0.0000
1,ENSG00000223972.6,DDX11L1,0.00000,0.0000,0.00000,0.0000,0.00000,0.00000,0.00000,0.000000,...,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.0000
2,ENSG00000310526.1,WASH7P,2.45431,1.9053,1.75253,2.3178,2.21944,1.66539,3.14825,0.565228,...,5.04503,2.04517,1.868420,1.507490,1.909350,3.126710,4.01324,4.92657,3.85789,2.2098
3,ENSG00000243485.6,MIR1302-2HG,0.00000,0.0000,0.00000,0.0000,0.00000,0.00000,0.00000,0.000000,...,0.00000,0.00000,0.000000,0.000000,0.000000,0.036257,0.00000,0.00000,0.00000,0.0000
4,ENSG00000237613.3,FAM138A,0.00000,0.0000,0.00000,0.0000,0.00000,0.00000,0.00000,0.012860,...,0.00000,0.00000,0.015325,0.013091,0.018168,0.000000,0.00000,0.00000,0.00000,0.0000

In [4]:
# check the size of the dataframe
df.shape

(74628, 70)

In [5]:
# check the data types of the columns
df.dtypes

Name                            str
Description                     str
Adipose_Subcutaneous        float64
Adipose_Visceral_Omentum    float64
Adrenal_Gland               float64
                             ...
Testis                      float64
Thyroid                     float64
Uterus                      float64
Vagina                      float64
Whole_Blood                 float64
Length: 70, dtype: object

In [6]:
# check the columns names
df.columns

Index(['Name', 'Description', 'Adipose_Subcutaneous',
       'Adipose_Visceral_Omentum', 'Adrenal_Gland', 'Artery_Aorta',
       'Artery_Coronary', 'Artery_Tibial', 'Bladder', 'Brain_Amygdala',
       'Brain_Anterior_cingulate_cortex_BA24', 'Brain_Caudate_basal_ganglia',
       'Brain_Cerebellar_Hemisphere', 'Brain_Cerebellum', 'Brain_Cortex',
       'Brain_Frontal_Cortex_BA9', 'Brain_Hippocampus', 'Brain_Hypothalamus',
       'Brain_Nucleus_accumbens_basal_ganglia', 'Brain_Putamen_basal_ganglia',
       'Brain_Spinal_cord_cervical_c-1', 'Brain_Substantia_nigra',
       'Breast_Mammary_Tissue', 'Cells_Cultured_fibroblasts',
       'Cells_EBV-transformed_lymphocytes', 'Cervix_Ectocervix',
       'Cervix_Endocervix', 'Colon_Sigmoid', 'Colon_Transverse',
       'Colon_Transverse_Mixed_Cell', 'Colon_Transverse_Mucosa',
       'Colon_Transverse_Muscularis', 'Esophagus_Gastroesophageal_Junction',
       'Esophagus_Mucosa', 'Esophagus_Muscularis', 'Fallopian_Tube',
       'Heart_Atrial_Appendage', 'Heart_Left_Ventricle', 'Kidney_Cortex',
       'Kidney_Medulla', 'Liver', 'Liver_Hepatocyte', 'Liver_Mixed_Cell',
       'Liver_Portal_Tract', 'Lung', 'Minor_Salivary_Gland', 'Muscle_Skeletal',
       'Nerve_Tibial', 'Ovary', 'Pancreas', 'Pancreas_Acini',
       'Pancreas_Islets', 'Pancreas_Mixed_Cell', 'Pituitary', 'Prostate',
       'Skin_Not_Sun_Exposed_Suprapubic', 'Skin_Sun_Exposed_Lower_leg',
       'Small_Intestine_Terminal_Ileum',
       'Small_Intestine_Terminal_Ileum_Lymphoid_Aggregate',
       'Small_Intestine_Terminal_Ileum_Mixed_Cell', 'Spleen', 'Stomach',
       'Stomach_Mixed_Cell', 'Stomach_Mucosa', 'Stomach_Muscularis', 'Testis',
       'Thyroid', 'Uterus', 'Vagina', 'Whole_Blood'],
      dtype='str')

In [7]:
# check for missing values
df.isnull().sum()

Name                        0
Description                 0
Adipose_Subcutaneous        0
Adipose_Visceral_Omentum    0
Adrenal_Gland               0
                           ..
Testis                      0
Thyroid                     0
Uterus                      0
Vagina                      0
Whole_Blood                 0
Length: 70, dtype: int64

In [8]:
# check the genes names
df[["Name", "Description"]].head(20)

                 Name      Description
0   ENSG00000290825.2         DDX11L16
1   ENSG00000223972.6          DDX11L1
2   ENSG00000310526.1           WASH7P
3   ENSG00000243485.6      MIR1302-2HG
4   ENSG00000237613.3          FAM138A
5   ENSG00000308361.1  ENSG00000308361
6   ENSG00000290826.2  ENSG00000290826
7   ENSG00000268020.3           OR4G4P
8   ENSG00000186092.7            OR4F5
9   ENSG00000241860.8  ENSG00000241860
10  ENSG00000308314.1  ENSG00000308314
11  ENSG00000233750.3           CICP27
12  ENSG00000308579.1  ENSG00000308579
13  ENSG00000268903.1  ENSG00000268903
14  ENSG00000269981.1  ENSG00000269981
15  ENSG00000239906.1  ENSG00000239906
16  ENSG00000222623.1       RNU6-1100P
17  ENSG00000241599.1  ENSG00000241599
18  ENSG00000308415.1          DDX11L2
19  ENSG00000310527.1           WASH9P

## Create the Gene-Tissue Expression Table

I will create a table where each row represents a gene and each column represents a tissue. The values represent the median TPM expression of each gene in each tissue.

In [9]:
# get all the tissue columns
tissue_cols = df.columns[2:]

print("Number of tissues:", len(tissue_cols))

Number of tissues: 68

In [10]:
# create a table with the gene information and tissue expression
gene_tissue_table = df[
    ["Name", "Description"] + list(tissue_cols)
].copy()

In [11]:
gene_tissue_table.head()

,Name,Description,Adipose_Subcutaneous,Adipose_Visceral_Omentum,Adrenal_Gland,Artery_Aorta,Artery_Coronary,Artery_Tibial,Bladder,Brain_Amygdala,...,Spleen,Stomach,Stomach_Mixed_Cell,Stomach_Mucosa,Stomach_Muscularis,Testis,Thyroid,Uterus,Vagina,Whole_Blood
0,ENSG00000290825.2,DDX11L16,0.00000,0.0000,0.00000,0.0000,0.00000,0.00000,0.00000,0.011780,...,0.00000,0.00000,0.014928,0.012652,0.015991,0.073208,0.00000,0.00000,0.00000,0.0000
1,ENSG00000223972.6,DDX11L1,0.00000,0.0000,0.00000,0.0000,0.00000,0.00000,0.00000,0.000000,...,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.0000
2,ENSG00000310526.1,WASH7P,2.45431,1.9053,1.75253,2.3178,2.21944,1.66539,3.14825,0.565228,...,5.04503,2.04517,1.868420,1.507490,1.909350,3.126710,4.01324,4.92657,3.85789,2.2098
3,ENSG00000243485.6,MIR1302-2HG,0.00000,0.0000,0.00000,0.0000,0.00000,0.00000,0.00000,0.000000,...,0.00000,0.00000,0.000000,0.000000,0.000000,0.036257,0.00000,0.00000,0.00000,0.0000
4,ENSG00000237613.3,FAM138A,0.00000,0.0000,0.00000,0.0000,0.00000,0.00000,0.00000,0.012860,...,0.00000,0.00000,0.015325,0.013091,0.018168,0.000000,0.00000,0.00000,0.00000,0.0000

save the table as a CSV without adding the pandas row numbers

In [12]:
gene_tissue_table.to_csv("../data/gene_tissue_table.csv", index=False)

In [13]:
#check the size of the new table
gene_tissue_table.shape

(74628, 70)

In [14]:
# check the last rows of the new table
gene_tissue_table.tail()

,Name,Description,Adipose_Subcutaneous,Adipose_Visceral_Omentum,Adrenal_Gland,Artery_Aorta,Artery_Coronary,Artery_Tibial,Bladder,Brain_Amygdala,...,Spleen,Stomach,Stomach_Mixed_Cell,Stomach_Mucosa,Stomach_Muscularis,Testis,Thyroid,Uterus,Vagina,Whole_Blood
74623,ENSG00000198695.2,MT-ND6,3580.83000,3704.71000,6334.180000,6153.05000,5154.8400,4711.95000,8608.33000,8611.21000,...,6156.630000,9501.860000,11307.400000,13053.10000,17327.100000,1728.010000,2456.380000,3684.300000,2261.660000,1351.94000
74624,ENSG00000210194.1,MT-TE,9.94868,8.87927,14.996800,19.22740,14.7159,14.68540,23.17160,21.37310,...,22.553300,27.708800,33.549800,44.33840,54.924100,2.348060,4.577450,8.959790,4.374740,4.18281
74625,ENSG00000198727.2,MT-CYB,24519.50000,26150.10000,29361.000000,13468.00000,16871.5000,13510.60000,23808.90000,32773.70000,...,12932.600000,27718.600000,22572.500000,31739.90000,26517.400000,15794.100000,20060.800000,15772.500000,12959.900000,3221.90000
74626,ENSG00000210195.2,MT-TT,0.00000,0.52678,0.657214,0.00000,0.0000,0.00000,0.00000,1.34734,...,0.643566,0.526479,0.431159,1.32891,0.715711,0.000000,0.000000,0.000000,0.000000,0.00000
74627,ENSG00000210196.2,MT-TP,1.31511,1.10991,1.524400,1.48577,1.5314,1.93504,1.60789,3.10255,...,0.971871,1.901460,2.147750,2.64756,3.772450,0.932806,0.909932,0.801636,0.732839,0.00000

In [15]:
#check if all the genes present and are all the tissue columns present
tissue_cols.tolist()

['Adipose_Subcutaneous',
 'Adipose_Visceral_Omentum',
 'Adrenal_Gland',
 'Artery_Aorta',
 'Artery_Coronary',
 'Artery_Tibial',
 'Bladder',
 'Brain_Amygdala',
 'Brain_Anterior_cingulate_cortex_BA24',
 'Brain_Caudate_basal_ganglia',
 'Brain_Cerebellar_Hemisphere',
 'Brain_Cerebellum',
 'Brain_Cortex',
 'Brain_Frontal_Cortex_BA9',
 'Brain_Hippocampus',
 'Brain_Hypothalamus',
 'Brain_Nucleus_accumbens_basal_ganglia',
 'Brain_Putamen_basal_ganglia',
 'Brain_Spinal_cord_cervical_c-1',
 'Brain_Substantia_nigra',
 'Breast_Mammary_Tissue',
 'Cells_Cultured_fibroblasts',
 'Cells_EBV-transformed_lymphocytes',
 'Cervix_Ectocervix',
 'Cervix_Endocervix',
 'Colon_Sigmoid',
 'Colon_Transverse',
 'Colon_Transverse_Mixed_Cell',
 'Colon_Transverse_Mucosa',
 'Colon_Transverse_Muscularis',
 'Esophagus_Gastroesophageal_Junction',
 'Esophagus_Mucosa',
 'Esophagus_Muscularis',
 'Fallopian_Tube',
 'Heart_Atrial_Appendage',
 'Heart_Left_Ventricle',
 'Kidney_Cortex',
 'Kidney_Medulla',
 'Liver',
 'Liver_Hepatocyte',
 'Liver_Mixed_Cell',
 'Liver_Portal_Tract',
 'Lung',
 'Minor_Salivary_Gland',
 'Muscle_Skeletal',
 'Nerve_Tibial',
 'Ovary',
 'Pancreas',
 'Pancreas_Acini',
 'Pancreas_Islets',
 'Pancreas_Mixed_Cell',
 'Pituitary',
 'Prostate',
 'Skin_Not_Sun_Exposed_Suprapubic',
 'Skin_Sun_Exposed_Lower_leg',
 'Small_Intestine_Terminal_Ileum',
 'Small_Intestine_Terminal_Ileum_Lymphoid_Aggregate',
 'Small_Intestine_Terminal_Ileum_Mixed_Cell',
 'Spleen',
 'Stomach',
 'Stomach_Mixed_Cell',
 'Stomach_Mucosa',
 'Stomach_Muscularis',
 'Testis',
 'Thyroid',
 'Uterus',
 'Vagina',
 'Whole_Blood']

In [16]:
# check how many tissue columns we have
len(tissue_cols)

68

In [17]:
# chech the data types
gene_tissue_table.dtypes

Name                            str
Description                     str
Adipose_Subcutaneous        float64
Adipose_Visceral_Omentum    float64
Adrenal_Gland               float64
                             ...
Testis                      float64
Thyroid                     float64
Uterus                      float64
Vagina                      float64
Whole_Blood                 float64
Length: 70, dtype: object

In [18]:
gene_tissue_table.isnull().sum()

Name                        0
Description                 0
Adipose_Subcutaneous        0
Adipose_Visceral_Omentum    0
Adrenal_Gland               0
                           ..
Testis                      0
Thyroid                     0
Uterus                      0
Vagina                      0
Whole_Blood                 0
Length: 70, dtype: int64

In [19]:
# check wheteher some genes are missing in every tissue

# keep only the tissue expression values
expression_table = gene_tissue_table[tissue_cols]

# find genes that have 0 TPM in every tissue
zero_genes = (expression_table.sum(axis=1) == 0)

# count how many genes have 0 expression everywhere
zero_genes.sum()

np.int64(13875)

In [20]:
# count genes that are not zero in every tissue
(~zero_genes).sum()

np.int64(60753)

We remove all-zero genes because they cannot be normalized and they do not help us understand which tissues a gene is associated with.

In [21]:
gene_tissue_table.drop(
    gene_tissue_table[zero_genes].index,
    inplace=True)

In [22]:
# check the data size after dropping genes with 0 expression in every tissue
gene_tissue_table.shape

(60753, 70)

## Normalize Gene Expression

For each gene, I will convert the TPM values into relative expression values so that the values across all tissues add up to 1.

In [23]:
# get only the tissue values
expression_table = gene_tissue_table[tissue_cols]

# get the total expression for each gene
gene_total = expression_table.sum(axis=1)

# divide each tissue value by the total for that gene
normaliz_expression = expression_table.div(gene_total, axis=0)

In [24]:
normaliz_expression.head()

,Adipose_Subcutaneous,Adipose_Visceral_Omentum,Adrenal_Gland,Artery_Aorta,Artery_Coronary,Artery_Tibial,Bladder,Brain_Amygdala,Brain_Anterior_cingulate_cortex_BA24,Brain_Caudate_basal_ganglia,...,Spleen,Stomach,Stomach_Mixed_Cell,Stomach_Mucosa,Stomach_Muscularis,Testis,Thyroid,Uterus,Vagina,Whole_Blood
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.021687,0.000000,0.019531,...,0.000000,0.000000,0.027482,0.023292,0.029439,0.134775,0.000000,0.000000,0.000000,0.00000
2,0.014339,0.011131,0.010239,0.013541,0.012967,0.00973,0.018393,0.003302,0.003814,0.003990,...,0.029475,0.011948,0.010916,0.008807,0.011155,0.018267,0.023447,0.028782,0.022539,0.01291
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.266933,0.000000,0.000000,0.000000,0.00000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.024759,0.025860,0.024015,...,0.000000,0.000000,0.029505,0.025204,0.034978,0.000000,0.000000,0.000000,0.000000,0.00000
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000

In [25]:
# check if each gene adds up to 1
normaliz_expression.sum(axis=1).head()

0    1.0
2    1.0
3    1.0
4    1.0
5    1.0
dtype: float64