# GTEx Gene Expression Data Exploration

This notebook is used to explore the GTEx V11 median TPM gene expression dataset.

The goal is to understand the structure of the data, check the genes and tissues, and prepare the dataset for further analysis.

In [2]:
%pip install pandas numpy matplotlib

Requirement already satisfied: pandas in c:\users\benso\appdata\local\programs\python\python312\lib\site-packages (3.0.1)
Requirement already satisfied: numpy in c:\users\benso\appdata\local\programs\python\python312\lib\site-packages (2.4.3)
Collecting matplotlib
  Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/04/93/0d239bde12b308262265c2d98909b2f0ecad2b5deeae96241642e822e9c7/matplotlib-3.11.2-cp312-cp312-win_amd64.whl.metadata
  Downloading matplotlib-3.11.2-cp312-cp312-win_amd64.whl.metadata (80 kB)
     ---------------------------------------- 0.0/80.3 kB ? eta -:--:--
     ----- ---------------------------------- 10.2/80.3 kB ? eta -:--:--
     -------------------------------------- 80.3/80.3 kB 897.7 kB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\benso\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\benso\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.3)
Collecting contourpy>=1.0.1 (from matplotlib)
  Obtaining dependency information for contourpy>=1.0.1 from https://files.pythonhosted.org/packages/50/a9/dab08786bb4d77ef9a046b3c1be923be4e73c5d07d91f5a54e8ea9b09e41/contourpy-1.4.0-cp312-cp312-win_amd64.whl.metadata
  Downloading contourpy-1.4.0-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib)
  Obtaining dependency information for cycler>=0.10 from https://files.pythonhosted.org/packages/e7/05/c19819d5e3d95294a6f5947fb9b9629efb316b96de511b418c53d245aae6/cycler-0.12.1-py3-none-any.whl.metadata
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Obtaining dependency information for fonttools>=4.28.2 from https://files.pythonhosted.org/packages/b5/f2/fd490f1ddf2e430289c13059982771e6b02a2bf37504401d2a5c53307892/fonttools-4.66.0-cp312-cp312-win_amd64.whl.metadata
  Downloading fonttools-4.66.0-cp312-cp312-win_amd64.whl.metadata (131 kB)
     ---------------------------------------- 0.0/131.7 kB ? eta -:--:--
     -------------------------------------- 131.7/131.7 kB 3.9 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Obtaining dependency information for kiwisolver>=1.3.1 from https://files.pythonhosted.org/packages/6e/7c/7b210498f9f92e1cd7855f260fa69ef056881087b199ee20c208f0e4189a/kiwisolver-1.5.1-cp312-cp312-win_amd64.whl.metadata
  Downloading kiwisolver-1.5.1-cp312-cp312-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\benso\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (26.0)
Collecting pillow>=9 (from matplotlib)
  Obtaining dependency information for pillow>=9 from https://files.pythonhosted.org/packages/45/89/da2f7971a317f83d807fdd4065c0af40208e59e692cc43d315a71a0e96d1/pillow-12.3.0-cp312-cp312-win_amd64.whl.metadata
  Downloading pillow-12.3.0-cp312-cp312-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Obtaining dependency information for pyparsing>=3 from https://files.pythonhosted.org/packages/38/bb/d215ee7c73b61497b28a5503f9f53523f294fcc936762b7caf90e0c1c2b5/pyparsing-3.3.3-py3-none-any.whl.metadata
  Downloading pyparsing-3.3.3-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: six>=1.5 in c:\users\benso\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading matplotlib-3.11.2-cp312-cp312-win_amd64.whl (9.3 MB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.4/9.3 MB 13.4 MB/s eta 0:00:01
   --- ------------------------------------ 0.9/9.3 MB 11.3 MB/s eta 0:00:01
   ------ --------------------------------- 1.5/9.3 MB 11.8 MB/s eta 0:00:01
   -------- ------------------------------- 2.1/9.3 MB 13.2 MB/s eta 0:00:01
   -------- ------------------------------- 2.1/9.3 MB 13.2 MB/s eta 0:00:01
   ------------ --------------------------- 2.9/9.3 MB 12.4 MB/s eta 0:00:01
   --------------- ------------------------ 3.5/9.3 MB 12.5 MB/s eta 0:00:01
   ------------------ --------------------- 4.2/9.3 MB 12.8 MB/s eta 0:00:01
   -------------------- ------------------- 4.9/9.3 MB 12.9 MB/s eta 0:00:01
   -------------------- ------------------- 4.9/9.3 MB 13.0 MB/s eta 0:00:01
   ------------------------ --------------- 5.7/9.3 MB 12.5 MB/s eta 0:00:01
   -------------------------- ------------- 6.3/9.3 MB 13.0 MB/s eta 0:00:01
   ----------------------------- ---------- 6.9/9.3 MB 13.0 MB/s eta 0:00:01
   -------------------------------- ------- 7.5/9.3 MB 13.3 MB/s eta 0:00:01
   ---------------------------------- ----- 8.2/9.3 MB 13.3 MB/s eta 0:00:01
   ---------------------------------- ----- 8.2/9.3 MB 13.3 MB/s eta 0:00:01
   ---------------------------------------  9.2/9.3 MB 13.3 MB/s eta 0:00:01
   ---------------------------------------- 9.3/9.3 MB 12.7 MB/s eta 0:00:00
Downloading contourpy-1.4.0-cp312-cp312-win_amd64.whl (234 kB)
   ---------------------------------------- 0.0/234.1 kB ? eta -:--:--
   --------------------------------------- 234.1/234.1 kB 14.0 MB/s eta 0:00:00
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.66.0-cp312-cp312-win_amd64.whl (2.5 MB)
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------- ----------------------------- 0.7/2.5 MB 21.1 MB/s eta 0:00:01
   ------------------- -------------------- 1.2/2.5 MB 19.3 MB/s eta 0:00:01
   ------------------------------ --------- 1.9/2.5 MB 15.1 MB/s eta 0:00:01
   ---------------------------------------- 2.5/2.5 MB 14.4 MB/s eta 0:00:00
Downloading kiwisolver-1.5.1-cp312-cp312-win_amd64.whl (70 kB)
   ---------------------------------------- 0.0/70.7 kB ? eta -:--:--
   ---------------------------------------- 70.7/70.7 kB ? eta 0:00:00
Downloading pillow-12.3.0-cp312-cp312-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   --- ------------------------------------ 0.6/7.2 MB 19.5 MB/s eta 0:00:01
   ------ --------------------------------- 1.2/7.2 MB 19.2 MB/s eta 0:00:01
   ---------- ----------------------------- 1.9/7.2 MB 17.0 MB/s eta 0:00:01
   ------------- -------------------------- 2.4/7.2 MB 15.6 MB/s eta 0:00:01
   ----------------- ---------------------- 3.2/7.2 MB 15.6 MB/s eta 0:00:01
   --------------------- ------------------ 3.9/7.2 MB 15.5 MB/s eta 0:00:01
   ----------------------- ---------------- 4.2/7.2 MB 15.0 MB/s eta 0:00:01
   ---------------------------- ----------- 5.2/7.2 MB 14.9 MB/s eta 0:00:01
   -------------------------------- ------- 5.8/7.2 MB 14.8 MB/s eta 0:00:01
   ----------------------------------- ---- 6.5/7.2 MB 14.8 MB/s eta 0:00:01
   ---------------------------------------  7.2/7.2 MB 14.9 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 14.4 MB/s eta 0:00:00
Downloading pyparsing-3.3.3-py3-none-any.whl (126 kB)
   ---------------------------------------- 0.0/126.4 kB ? eta -:--:--
   ---------------------------------------- 126.4/126.4 kB ? eta 0:00:00
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
Successfully installed contourpy-1.4.0 cycler-0.12.1 fonttools-4.66.0 kiwisolver-1.5.1 matplotlib-3.11.2 pillow-12.3.0 pyparsing-3.3.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
file_name = "../data/GTEx_Analysis_2025-08-22_v11_RNASeQCv2.4.3_gene_median_tpm.gct.gz"

df = pd.read_csv(
    file_name,
    sep="\t",
    skiprows=2
)

df.head()

,Name,Description,Adipose_Subcutaneous,Adipose_Visceral_Omentum,Adrenal_Gland,Artery_Aorta,Artery_Coronary,Artery_Tibial,Bladder,Brain_Amygdala,...,Spleen,Stomach,Stomach_Mixed_Cell,Stomach_Mucosa,Stomach_Muscularis,Testis,Thyroid,Uterus,Vagina,Whole_Blood
0,ENSG00000290825.2,DDX11L16,0.00000,0.0000,0.00000,0.0000,0.00000,0.00000,0.00000,0.011780,...,0.00000,0.00000,0.014928,0.012652,0.015991,0.073208,0.00000,0.00000,0.00000,0.0000
1,ENSG00000223972.6,DDX11L1,0.00000,0.0000,0.00000,0.0000,0.00000,0.00000,0.00000,0.000000,...,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.0000
2,ENSG00000310526.1,WASH7P,2.45431,1.9053,1.75253,2.3178,2.21944,1.66539,3.14825,0.565228,...,5.04503,2.04517,1.868420,1.507490,1.909350,3.126710,4.01324,4.92657,3.85789,2.2098
3,ENSG00000243485.6,MIR1302-2HG,0.00000,0.0000,0.00000,0.0000,0.00000,0.00000,0.00000,0.000000,...,0.00000,0.00000,0.000000,0.000000,0.000000,0.036257,0.00000,0.00000,0.00000,0.0000
4,ENSG00000237613.3,FAM138A,0.00000,0.0000,0.00000,0.0000,0.00000,0.00000,0.00000,0.012860,...,0.00000,0.00000,0.015325,0.013091,0.018168,0.000000,0.00000,0.00000,0.00000,0.0000

In [5]:
# check the size of the dataframe
df.shape

(74628, 70)

In [6]:
# check the data types of the columns
df.dtypes

Name                            str
Description                     str
Adipose_Subcutaneous        float64
Adipose_Visceral_Omentum    float64
Adrenal_Gland               float64
                             ...
Testis                      float64
Thyroid                     float64
Uterus                      float64
Vagina                      float64
Whole_Blood                 float64
Length: 70, dtype: object

In [7]:
# check the columns names
df.columns

Index(['Name', 'Description', 'Adipose_Subcutaneous',
       'Adipose_Visceral_Omentum', 'Adrenal_Gland', 'Artery_Aorta',
       'Artery_Coronary', 'Artery_Tibial', 'Bladder', 'Brain_Amygdala',
       'Brain_Anterior_cingulate_cortex_BA24', 'Brain_Caudate_basal_ganglia',
       'Brain_Cerebellar_Hemisphere', 'Brain_Cerebellum', 'Brain_Cortex',
       'Brain_Frontal_Cortex_BA9', 'Brain_Hippocampus', 'Brain_Hypothalamus',
       'Brain_Nucleus_accumbens_basal_ganglia', 'Brain_Putamen_basal_ganglia',
       'Brain_Spinal_cord_cervical_c-1', 'Brain_Substantia_nigra',
       'Breast_Mammary_Tissue', 'Cells_Cultured_fibroblasts',
       'Cells_EBV-transformed_lymphocytes', 'Cervix_Ectocervix',
       'Cervix_Endocervix', 'Colon_Sigmoid', 'Colon_Transverse',
       'Colon_Transverse_Mixed_Cell', 'Colon_Transverse_Mucosa',
       'Colon_Transverse_Muscularis', 'Esophagus_Gastroesophageal_Junction',
       'Esophagus_Mucosa', 'Esophagus_Muscularis', 'Fallopian_Tube',
       'Heart_Atrial_Appendage', 'Heart_Left_Ventricle', 'Kidney_Cortex',
       'Kidney_Medulla', 'Liver', 'Liver_Hepatocyte', 'Liver_Mixed_Cell',
       'Liver_Portal_Tract', 'Lung', 'Minor_Salivary_Gland', 'Muscle_Skeletal',
       'Nerve_Tibial', 'Ovary', 'Pancreas', 'Pancreas_Acini',
       'Pancreas_Islets', 'Pancreas_Mixed_Cell', 'Pituitary', 'Prostate',
       'Skin_Not_Sun_Exposed_Suprapubic', 'Skin_Sun_Exposed_Lower_leg',
       'Small_Intestine_Terminal_Ileum',
       'Small_Intestine_Terminal_Ileum_Lymphoid_Aggregate',
       'Small_Intestine_Terminal_Ileum_Mixed_Cell', 'Spleen', 'Stomach',
       'Stomach_Mixed_Cell', 'Stomach_Mucosa', 'Stomach_Muscularis', 'Testis',
       'Thyroid', 'Uterus', 'Vagina', 'Whole_Blood'],
      dtype='str')

In [8]:
# check for missing values
df.isnull().sum()

Name                        0
Description                 0
Adipose_Subcutaneous        0
Adipose_Visceral_Omentum    0
Adrenal_Gland               0
                           ..
Testis                      0
Thyroid                     0
Uterus                      0
Vagina                      0
Whole_Blood                 0
Length: 70, dtype: int64

In [9]:
# check the genes names
df[["Name", "Description"]].head(20)

                 Name      Description
0   ENSG00000290825.2         DDX11L16
1   ENSG00000223972.6          DDX11L1
2   ENSG00000310526.1           WASH7P
3   ENSG00000243485.6      MIR1302-2HG
4   ENSG00000237613.3          FAM138A
5   ENSG00000308361.1  ENSG00000308361
6   ENSG00000290826.2  ENSG00000290826
7   ENSG00000268020.3           OR4G4P
8   ENSG00000186092.7            OR4F5
9   ENSG00000241860.8  ENSG00000241860
10  ENSG00000308314.1  ENSG00000308314
11  ENSG00000233750.3           CICP27
12  ENSG00000308579.1  ENSG00000308579
13  ENSG00000268903.1  ENSG00000268903
14  ENSG00000269981.1  ENSG00000269981
15  ENSG00000239906.1  ENSG00000239906
16  ENSG00000222623.1       RNU6-1100P
17  ENSG00000241599.1  ENSG00000241599
18  ENSG00000308415.1          DDX11L2
19  ENSG00000310527.1           WASH9P